let a=5;
let b= ++a;
console.log(a);
console.log(b);
let a2=5;
let b2=a2++;
console.log(a2);
console.log(b2);
let n=20;
console.log(--n);
console.log(n--);
console.log(n);
let x= 8;
console.log(x++);
console.log(++x);
console.log(x);
let a3=3;
let b3=a3++ + ++a3;
console.log(a3);
console.log(b3);
let num = 10;
console.log(num--);
console.log(--num);
console.log(num);
let x2 = 2;
let y2= ++x2 + x2++;
console.log(x2);
console.log(y2);
let a4 = 7;
console.log(a4++);
console.log(a4++);
console.log(a4);
let n2 = 4;
let result = n2-- + --n2;
console.log(n2);
console.log(result);
let x3 = 1;
console.log(++x3 + ++x3);
console.log(x3);
let a5 = 6;
let b5 = --a5 + a5--;
console.log(a5);
console.log(b5);
let num2 = 9;
console.log(num2++);
console.log(num2);
console.log(++num2);
let x4 = 12;
let y4 = x4-- + x4++;
console.log(x4);
console.log(y4);
